#!/bin/bash
# Bibliotecas de funciones para wm.
# By Pablo Niklas.
#

function Reducir {

    # Ojo que no pasa la informacion EXIF, hay que reescribirla.
    exit 1

    echo -n "  Reduciendo a resolucion HD..."
    X_IMAGE=`identify -format %w "$1"`
    Y_IMAGE=`identify -format %h "$1"`

    if [ $X_IMAGE -gt $Y_IMAGE ]; then
        # Landscape
        echo -n "Landscape..."
        convert $1 -resize 1920x1080 $1
        RC=$?; echo "RC=$RC"
    else
        # Portrait
        echo -n "Portrait..."
        convert $1 -resize 1080x1920 $1
        RC=$?; echo "RC=$RC"
    fi
}

function TransferirEXIF {

    # Transferir los EXIF - http://ninedegreesbelow.com/photography/exiftool-commands.html
    echo -n "  Transfiriendo informacion EXIF..."
    exiftool -tagsfromfile "$1"  -all:all -r -overwrite_original "$2" >/dev/null 2>&1
    RC=$?; echo "RC=$RC"
}

function MarcaAgua {

    COLORSPACE="sRGB"
    OFFSET_X=20
    OFFSET_Y=20

    IMAGE="$1"
    echo "Procesando imagen $IMAGE:"
    NAME=`echo "$IMAGE" | cut -f1 -d.`
    EXT=`echo "$IMAGE" | cut -f2 -d.`

    if [ $EXT=="CR2" ]; then
        EXT="png"       #PNG soporta transparencias.
    fi

    X_IMAGE=`identify -format %w "$IMAGE"`
    Y_IMAGE=`identify -format %h "$IMAGE"`

    echo "  Resolucion: $X_IMAGE x $Y_IMAGE"
    echo -n "  Generando marca de agua..."
  	#convert -size ${X_IMAGE}x${Y_IMAGE} xc:transparent -colorspace $COLORSPACE -fill '#0008' \
  	#	-draw "rectangle 0,$Y_IMAGE $X_IMAGE,$(($Y_IMAGE-$Y_WM-5))" "/tmp/$IMAGE.$$.1.$EXT"
    convert -size ${X_IMAGE}x${Y_IMAGE} xc:transparent -colorspace $COLORSPACE  -fill '#0000' \
    	-draw "rectangle 0,$Y_IMAGE $X_IMAGE,$(($Y_IMAGE-$Y_WM-5))" "/tmp/$IMAGE.$$.1.$EXT"
    RC=$?; echo "RC=$RC"
    if [ $RC -ne 0 ]; then
        exit $RC
    fi

    if [ $X_IMAGE -gt $Y_IMAGE ]; then
        # Landscape
        RAZON=`echo scale=2\; $Y_IMAGE/$Y_WM/12*100 | bc -l`
    else
        # Portrait
        RAZON=`echo scale=2\; $X_IMAGE/$X_WM/12*100 | bc -l`
    fi

    echo -n "  Reescalando (al $RAZON%)... "
    composite -dissolve 100% -gravity $WHERE -quality 100 -colorspace $COLORSPACE \( $WM -resize $RAZON% \) \
    	"/tmp/$IMAGE.$$.1.$EXT" "/tmp/$IMAGE.$$.2.$EXT"
    RC=$?; echo "RC=$RC"
    if [ $RC -ne 0 ]; then
        exit $RC
    fi
    echo -n "  Estampando marca de agua..."
    composite -gravity center -colorspace $COLORSPACE -geometry -$OFFSET_X-$OFFSET_Y \
      -quality 100 "/tmp/$IMAGE.$$.2.$EXT" "$IMAGE" "${NAME}_$MP.${EXT}"
    RC=$?; echo "RC=$RC"
    if [ $RC -ne 0 ]; then
        exit $RC
    fi

    TransferirEXIF "$IMAGE" "${NAME}_$MP.${EXT}"

    echo -n "  Convertir a JPG..."
    convert "${NAME}_$MP.${EXT}" "${NAME}_$MP.jpg"
    RC=$?; echo "RC=$RC"
    if [ $RC -ne 0 ]; then
        exit $RC
    fi

    TransferirEXIF "${NAME}_$MP.${EXT}" "${NAME}_$MP.jpg"

    rm -f "/tmp/$IMAGE.$$.2.$EXT" "/tmp/$IMAGE.$$.1.$EXT" "${NAME}_$MP.${EXT}"
}
