#!/bin/bash
# Script para estampar marca de agua.
# By Pablo Niklas.
#

source `dirname $0`/wm_lib
source `dirname $0`/lib_cpu

# Inicializo
#WM=/u02/Gimp/MarcasDeAgua/Watermark01.png
#WM=/u02/Gimp/MarcasDeAgua/Watermark02.png
WM=/u02/Gimp/MarcasDeAgua/Watermark03.png

SCALE=100
TMP=${TMP:-/tmp}

# Marca de procesamiento
MP="pn"

# Posicion de la marca de agua: http://www.imagemagick.org/script/command-line-options.php#gravity
# NorthWest, North, NorthEast, West, Center, East, SouthWest, South, SouthEast
DONDE=SouthEast

# Resolucion de la marca de agua
X_WM=`identify -format %w $WM`
X_WM=`echo $X_WM*$SCALE/100 | bc`

Y_WM=`identify -format %h $WM`
Y_WM=`echo $Y_WM*$SCALE/100 | bc`

echo "Info de la marca de agua ($WM) ===> $X_WM x $Y_WM (Escala $SCALE%)"

# Bucle principal
if [ -z "$1" ]; then
    echo "AVISO: No se especificaron archivos. Se procesaran todos los que se encuentren en el directorio."

    file -i * | grep image | awk -F':' '{ print $1 }' | grep -v _$MP.* | while read IMAGE;  do

        # Creo unidad de trabajo.
        NAME=`echo "$IMAGE" | cut -f1 -d.`
        WORK_UNIT="$TMP/wm_${NAME}_$$.sh"
        echo "Generando script de unidad de trabajo: $WORK_UNIT"

        echo '#!/bin/bash' > $WORK_UNIT
        echo >> $WORK_UNIT
        echo source `dirname $0`/wm_lib >> $WORK_UNIT
        echo >> $WORK_UNIT
        echo WM=$WM >> $WORK_UNIT
        echo SCALE=$SCALE >> $WORK_UNIT
        echo DONDE=$DONDE >> $WORK_UNIT
        echo MP=$MP >> $WORK_UNIT
        echo X_WM=$X_WM >> $WORK_UNIT
        echo Y_WM=$Y_WM >> $WORK_UNIT
        echo >> $WORK_UNIT
        echo MarcaAgua $IMAGE >> $WORK_UNIT
        echo >> $WORK_UNIT
        echo exit 0 >> $WORK_UNIT
        chmod u+x $WORK_UNIT

    done

    echo "Ejecutando conversion en forma paralela."
    echo
    paralelo $TMP/wm_*_$$.sh

    echo
    echo "Borrando archivos temporales."
    rm -f $TMP/wm_*_$$.sh

    exit 0
else
    MarcaAgua $1
fi

# Para evaluar mas adelante.
# convert -border 11x10 -bordercolor "#FFFFFF" Flores\ macro.png Flores\ macro_borde.png
# convert -font TerminalDosis-Medium.otf -pointsize 100 -background "#000000C0" -fill white -gravity SouthEast -size 800 -direction left-to-right label:@text.txt input.jpg +swap -composite output.jpg
