#!/bin/bash
# Script para estampar marca de agua.
# By Pablo Niklas.
#

source `dirname $0`/wm_lib
source `dirname $0`/lib_cpu

# Inicializo
#WM=/u02/Gimp/MarcasDeAgua/Watermark01.png
#WM=/u02/Gimp/MarcasDeAgua/Watermark02.png
WM=/u02/Gimp/MarcasDeAgua/Watermark03.png

SCALE=100

# Marca de procesamiento
MP="pn"

# Posicion de la marca de agua: http://www.imagemagick.org/script/command-line-options.php#gravity
# NorthWest, North, NorthEast, West, Center, East, SouthWest, South, SouthEast
DONDE=SouthEast

# Resolucion de la marca de agua
X_WM=`identify -format %w $WM`
X_WM=`echo $X_WM*$SCALE/100 | bc`

Y_WM=`identify -format %h $WM`
Y_WM=`echo $Y_WM*$SCALE/100 | bc`

echo "Info de la marca de agua ($WM) ===> $X_WM x $Y_WM (Escala $SCALE%)"

# Bucle principal
if [ -z "$1" ]; then
    echo "AVISO: No se especificaron archivos. Se procesaran todos los que se encuentren en el directorio."

    file -i * | grep image | awk -F':' '{ print $1 }' | grep -v _$MP.* | while read IMAGE;  do

        # Creo unidad de trabajo.
        WORK_UNIT="$TMP/wm_$IMAGE_$$.sh"

        echo "Programando unidad de trabajo: $WORK_UNIT"

        echo '#!/bin/bash' > $WORK_UNIT
        echo >> $WORK_UNIT
        echo source `dirname $0`/wm_lib >> $WORK_UNIT
        echo >> $WORK_UNIT
        echo MarcaAgua $IMAGE >> $WORK_UNIT
        echo >> $WORK_UNIT
        echo exit 0 >> $WORK_UNIT

    done
    exit 0
else
    MarcaAgua $1
fi

# Para evaluar mas adelante.
# convert -border 11x10 -bordercolor "#FFFFFF" Flores\ macro.png Flores\ macro_borde.png
# convert -font TerminalDosis-Medium.otf -pointsize 100 -background "#000000C0" -fill white -gravity SouthEast -size 800 -direction left-to-right label:@text.txt input.jpg +swap -composite output.jpg


